module.exports.currentUser = {
  UserID: 1,
  Username: 'Ewald23',
  ThumbnailURL: 'https://s3.amazonaws.com/uifaces/faces/twitter/bowbrick/128.jpg',
};

module.exports.questionData = [
  {
    QuestionID: 21,
    Content: 'Animi nemo rerum. Quia maiores ea saepe. Temporibus dicta dolor ipsa omnis.?',
    PostedDate: '2018-07-01',
    UserID: 8,
    User: {
      Username: 'Genesis.Kunde93',
      ProfileURL: 'https://localhost:3000/users/8/profile',
      ThumbnailURL: 'https://s3.amazonaws.com/uifaces/faces/twitter/brandonflatsoda/128.jpg',
      SignUpDate: '2018-11-08',
      CitiesVisited: 4,
      HelpfulVotes: 12,
      HomeCity: 'Lake Imaside, Alaska',
      Category: 'Contributor',
      Ranking: 2,
      'ReviewDistribution.Excellent': 10,
      'ReviewDistribution.VeryGood': 1,
      'ReviewDistribution.Average': 1,
      'ReviewDistribution.Poor': 7,
      'ReviewDistribution.Terrible': 1,
    },
    Answers: [
      {
        id: 101,
        Content: 'Repellendus et non harum molestias aut sit. Omnis corrupti temporibus esse. Non sunt nisi velit enim mollitia. Quibusdam voluptate aut rem perferendis nostrum possimus quia omnis.',
        UserID: 40,
        QuestionID: 21,
        Votes: 9,
      },
      {
        id: 102,
        Content: 'Numquam tempora et repudiandae. Veritatis quasi eligendi facilis eum repellat commodi ut officiis. Quia velit veritatis illo necessitatibus. Aliquid pariatur quibusdam eaque.',
        UserID: 78,
        QuestionID: 21,
        Votes: 1,
      },
      {
        id: 103,
        Content: 'Fugit quia a. Laboriosam nesciunt minus expedita quia quasi optio id. Rerum ut dolorem. Quia dolorem blanditiis. Culpa pariatur qui quia consequatur quaerat totam assumenda ut et. Non cupiditate dolor libero ipsum suscipit itaque accusantium.',
        UserID: 83,
        QuestionID: 21,
        Votes: 0,
      },
      {
        id: 104,
        Content: 'Consequuntur facere consequuntur ullam. Laudantium maiores asperiores aperiam. Exercitationem consequatur qui perspiciatis magni.',
        UserID: 74,
        QuestionID: 21,
        Votes: 17,
      },
      {
        id: 105,
        Content: 'Nisi ut voluptatem quos quidem et mollitia. Asperiores ratione eaque perspiciatis suscipit quia tempore minima. Error exercitationem temporibus cum enim nulla et non illo.',
        UserID: 49,
        QuestionID: 21,
        Votes: 17,
      },
    ],
    AnswersUsers: [
      {
        id: 40,
        Username: 'Ruby.Buckridge',
        SignUpDate: '2018-10-02',
        CitiesVisited: 11,
        ProfileURL: 'https://localhost:3000/users/40/profile',
        HelpfulVotes: 1,
        ThumbnailURL: 'https://s3.amazonaws.com/uifaces/faces/twitter/cadikkara/128.jpg',
        Contributions: 3,
        Photos: 1,
        Ranking: 1,
        HomeCity: 'Port Marinaton, Wisconsin',
        Category: 'Contributor',
        'ReviewDistribution.Excellent': 8,
        'ReviewDistribution.VeryGood': 3,
        'ReviewDistribution.Average': 4,
        'ReviewDistribution.Poor': 3,
        'ReviewDistribution.Terrible': 0,
      },
      {
        id: 78,
        Username: 'Stephanie_Ledner12',
        SignUpDate: '2018-11-08',
        CitiesVisited: 3,
        ProfileURL: 'https://localhost:3000/users/78/profile',
        HelpfulVotes: 9,
        ThumbnailURL: 'https://s3.amazonaws.com/uifaces/faces/twitter/haydn_woods/128.jpg',
        Contributions: 10,
        Photos: 15,
        Ranking: 2,
        HomeCity: 'East Tavaresberg, Wyoming',
        Category: 'Contributor',
        'ReviewDistribution.Excellent': 3,
        'ReviewDistribution.VeryGood': 14,
        'ReviewDistribution.Average': 2,
        'ReviewDistribution.Poor': 8,
        'ReviewDistribution.Terrible': 11,
      },
      {
        id: 83,
        Username: 'Laila.Simonis',
        SignUpDate: '2018-05-02',
        CitiesVisited: 1,
        ProfileURL: 'https://localhost:3000/users/83/profile',
        HelpfulVotes: 9,
        ThumbnailURL: 'https://s3.amazonaws.com/uifaces/faces/twitter/kucingbelang4/128.jpg',
        Contributions: 10,
        Photos: 3,
        Ranking: 4,
        HomeCity: 'Antoniaville, Connecticut',
        Category: 'Contributor',
        'ReviewDistribution.Excellent': 10,
        'ReviewDistribution.VeryGood': 6,
        'ReviewDistribution.Average': 1,
        'ReviewDistribution.Poor': 8,
        'ReviewDistribution.Terrible': 4,
      },
      {
        id: 74,
        Username: 'Daphnee.Runolfsson72',
        SignUpDate: '2018-05-12',
        CitiesVisited: 10,
        ProfileURL: 'https://localhost:3000/users/74/profile',
        HelpfulVotes: 4,
        ThumbnailURL: 'https://s3.amazonaws.com/uifaces/faces/twitter/VMilescu/128.jpg',
        Contributions: 10,
        Photos: 12,
        Ranking: 2,
        HomeCity: 'East Keenanland, Alaska',
        Category: 'Contributor',
        'ReviewDistribution.Excellent': 12,
        'ReviewDistribution.VeryGood': 6,
        'ReviewDistribution.Average': 10,
        'ReviewDistribution.Poor': 15,
        'ReviewDistribution.Terrible': 12,
      },
      {
        id: 49,
        Username: 'Leopoldo_Graham',
        SignUpDate: '2017-12-21',
        CitiesVisited: 8,
        ProfileURL: 'https://localhost:3000/users/49/profile',
        HelpfulVotes: 18,
        ThumbnailURL: 'https://s3.amazonaws.com/uifaces/faces/twitter/evanshajed/128.jpg',
        Contributions: 9,
        Photos: 4,
        Ranking: 3,
        HomeCity: 'New Tremaynemouth, Arkansas',
        Category: 'Contributor',
        'ReviewDistribution.Excellent': 11,
        'ReviewDistribution.VeryGood': 10,
        'ReviewDistribution.Average': 6,
        'ReviewDistribution.Poor': 0,
        'ReviewDistribution.Terrible': 0,
      },
    ],
  },
];
